Script started on Mon 07 Sep 2020 12:27:02 PM EDT
[?1034hbash-4.2$ cd ~/os161/root/
bash-4.2$ cp /opt/apps/sys161-1.14/sys161.conf.sample sys161.conf 
bash-4.2$ sys161 kernel
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #2)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p p /sbin/poweroff
Operation took 0.000159280 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 4792409126 cycles (31662942k, 18u, 4760746166i)
sys161: 19751 irqs 6 exns 0r/0w disk 20r/695w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 191.689048 seconds (25.001 mhz)
sys161: Elapsed virtual time: 191.696365040 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Mon 07 Sep 2020 12:31:51 PM EDT
